### PR TITLE
Improvement: Add ability to refresh an access token

### PR DESCRIPTION
**Pull request by TheBerg**
Some servers requires the client to refresh their access token periodically. This adds that functionality to this library.

### CODE REVIEW

**Comment by bpedroza** [comment]
Thanks for your contribution. The code looks good. Please just update the copy/pasted method description.

I'm also not sure if allowing additional post parameters might be needed in some use cases, but we can always add that later if people ask for it.

**Comment by TheBerg** [comment]
@bpedroza Thanks! Updated. 

I had updated it earlier, but spilled water on my laptop and lost that original branch. 🤪😱🤣

**Review by bpedroza — APPROVED** [review]

**Comment by bpedroza** [comment]
Looks good. Thank you again. I'll get a new release out Today or tomorrow.

**Comment by TheBerg** [comment]
Thank you so much! You rock!!!

**Comment by bpedroza** [comment]
I just realized the access token is not required for exchanging a refresh token. Is there a reason you included it here?

**Comment by TheBerg** [comment]
I'm dumb and thought you needed it. I will PR to remove that.

**Comment by bpedroza** [comment]
It's OK. I'm working on it now. You left a few things in the tests too. Just double checking before I removed it.

**Pull request merged**
